@host = http://localhost:8080/2015-03-31/functions/function/invocations
# @host = 

### Trigger CloudWatch Log Event
POST {{host}}
Content-Type: application/json

{
  "awslogs": {
    "data": "ログデータ"
  }
}
